import logo from "./img/logo.png";
import { IChatPreviewItem } from "./components/Chat/Preview/Item/Item";

// test data
export const testData: IChatPreviewItem[] = [
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: new Date(),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
];
