import logo from "./img/logo.png";
import { IChatPreviewItem } from "./components/Chat/Preview/Item/Item";

const randomDate = (start: Date, end: Date) => {
    return new Date(
        start.getTime() + Math.random() * (end.getTime() - start.getTime())
    );
};

// test data
export const testData: IChatPreviewItem[] = [
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
    {
        icon: logo,
        name: "Group Chat",
        date: randomDate(new Date(2019, 0, 1), new Date()),
        author: "Ruslan",
        message: "Hello World! I am going to use all this line! Why not?",
    },
];
